io:
  location: <YOUR FOLDER HERE>
  file_name: <YOUR FILE HERE>
clients:
  - name: api-engine
    type: <RESOURCE TYPE HERE SEE configs.go Resource_XXX constants>
    path: <YOUR URL HERE>
    headers:
      <HEADER KEY>: <HEADER VALUE>
  - name: no-existing-client
